version: "3.1"

services:
    api:
        build: .
        command: npm start
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        ports:
            - 8080:8080

volumes:
    data:
